# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dragonvault.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dragonvault.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11\x64ragonvault.proto\"\x07\n\x05\x45mpty\")\n\x04User\x12\x10\n\x08userName\x18\x01 \x01(\t\x12\x0f\n\x07ip_addr\x18\x02 \x01(\t\"u\n\x04Room\x12\x10\n\x08roomName\x18\x01 \x01(\t\x12\x17\n\x0f\x61\x63tiveUserCount\x18\x02 \x01(\x05\x12\x1a\n\x0b\x61\x63tiveUsers\x18\x03 \x03(\x0b\x32\x05.User\x12\x0e\n\x06status\x18\x04 \x01(\x05\x12\x16\n\x0estatus_message\x18\x05 \x01(\t\"\x12\n\x03Url\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x12\n\x03\x41\x63k\x12\x0b\n\x03msg\x18\x01 \x01(\t2\xb1\x01\n\x0b\x44ragonvault\x12\x1c\n\tListRooms\x12\x06.Empty\x1a\x05.Room0\x01\x12\x17\n\x08JoinRoom\x12\x05.Room\x1a\x04.Ack\x12\x19\n\nCreateRoom\x12\x05.Room\x1a\x04.Ack\x12\x18\n\x08InfoRoom\x12\x05.Room\x1a\x05.Room\x12\x17\n\tSubmitUrl\x12\x04.Url\x1a\x04.Ack\x12\x1d\n\rStartDownload\x12\x06.Empty\x1a\x04.Ackb\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=28,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userName', full_name='User.userName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip_addr', full_name='User.ip_addr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=71,
)


_ROOM = _descriptor.Descriptor(
  name='Room',
  full_name='Room',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roomName', full_name='Room.roomName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activeUserCount', full_name='Room.activeUserCount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activeUsers', full_name='Room.activeUsers', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='Room.status', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status_message', full_name='Room.status_message', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=190,
)


_URL = _descriptor.Descriptor(
  name='Url',
  full_name='Url',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='Url.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=210,
)


_ACK = _descriptor.Descriptor(
  name='Ack',
  full_name='Ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='Ack.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=230,
)

_ROOM.fields_by_name['activeUsers'].message_type = _USER
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Room'] = _ROOM
DESCRIPTOR.message_types_by_name['Url'] = _URL
DESCRIPTOR.message_types_by_name['Ack'] = _ACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'dragonvault_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'dragonvault_pb2'
  # @@protoc_insertion_point(class_scope:User)
  })
_sym_db.RegisterMessage(User)

Room = _reflection.GeneratedProtocolMessageType('Room', (_message.Message,), {
  'DESCRIPTOR' : _ROOM,
  '__module__' : 'dragonvault_pb2'
  # @@protoc_insertion_point(class_scope:Room)
  })
_sym_db.RegisterMessage(Room)

Url = _reflection.GeneratedProtocolMessageType('Url', (_message.Message,), {
  'DESCRIPTOR' : _URL,
  '__module__' : 'dragonvault_pb2'
  # @@protoc_insertion_point(class_scope:Url)
  })
_sym_db.RegisterMessage(Url)

Ack = _reflection.GeneratedProtocolMessageType('Ack', (_message.Message,), {
  'DESCRIPTOR' : _ACK,
  '__module__' : 'dragonvault_pb2'
  # @@protoc_insertion_point(class_scope:Ack)
  })
_sym_db.RegisterMessage(Ack)



_DRAGONVAULT = _descriptor.ServiceDescriptor(
  name='Dragonvault',
  full_name='Dragonvault',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=233,
  serialized_end=410,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListRooms',
    full_name='Dragonvault.ListRooms',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_ROOM,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='JoinRoom',
    full_name='Dragonvault.JoinRoom',
    index=1,
    containing_service=None,
    input_type=_ROOM,
    output_type=_ACK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateRoom',
    full_name='Dragonvault.CreateRoom',
    index=2,
    containing_service=None,
    input_type=_ROOM,
    output_type=_ACK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='InfoRoom',
    full_name='Dragonvault.InfoRoom',
    index=3,
    containing_service=None,
    input_type=_ROOM,
    output_type=_ROOM,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SubmitUrl',
    full_name='Dragonvault.SubmitUrl',
    index=4,
    containing_service=None,
    input_type=_URL,
    output_type=_ACK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StartDownload',
    full_name='Dragonvault.StartDownload',
    index=5,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_ACK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DRAGONVAULT)

DESCRIPTOR.services_by_name['Dragonvault'] = _DRAGONVAULT

# @@protoc_insertion_point(module_scope)
